{{/*
ServiceAccount。
*/}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litefuse.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "litefuse.labels" . | nindent 4 }}
{{- end }}
